class BookTester{
    public static void main(String b[]){
	System.out.println("Creating 1st copy of the Book");
    Book book = new Book();
	book.name = "The God of Small Things";
	book.price = 350;
    book.type = "Fiction";
    book.author = "Arundhati Roy";
	book.publicationName = "Roli books";
	book.noOfPages = 300;
	book.gainKnowledge();
	//System.out.println(book.name +" "+ book.type + " " + book.price + " " + book.author + " " + book.publicationName + " " + book.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 2nd copy of the Book");
    //Book book1 = new Book();
	book.name = "The Immortals of Meluha";
	book.price = 500;
    book.type = "Mythological Fiction";
    book.author = "Amish Tripathi ";
	book.publicationName = "Rupa publications";
	book.noOfPages = 300;
	book.gainKnowledge();
	//System.out.println(book1.name +" "+ book1.type + " " + book1.price + " " + book1.author + " " + book1.publicationName + " " + book1.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 3rd copy of the Book");
    //Book book2 = new Book();
	book.name = "Half Girlfriend";
	book.price = 400;
    book.type = "Love";
    book.author = "Chetan Bhagat";
	book.publicationName = "APK publications";
	book.noOfPages = 200;
	book.gainKnowledge();
	//System.out.println(book2.name +" "+ book2.type + " " + book2.price + " " + book2.author + " " + book2.publicationName + " " + book2.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 4th copy of the Book");
    //Book book3 = new Book();
	book.name = "Train to Pakistan";
	book.price = 600;
    book.type = "Historical Fiction";
    book.author = "Khushwant Singh";
	book.publicationName = "Historical publications";
	book.noOfPages = 350;
	book.gainKnowledge();
	//System.out.println(book3.name +" "+ book3.type + " " + book3.price + " " + book3.author + " " + book3.publicationName + " " + book3.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 5th copy of the Book");
    //Book book4 = new Book();
	book.name = "The White Tiger";
	book.price = 1000;
    book.type = "Literary Fiction";
    book.author = "Aravind Adiga";
	book.publicationName = "Ravi publications";
	book.noOfPages = 600;
	book.gainKnowledge();
	//System.out.println(book4.name +" "+ book4.type + " " + book4.price + " " + book4.author + " " + book4.publicationName + " " + book4.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 6th copy of the Book");
    //Book book5 = new Book();
	book.name = "The Shiva Trilogy";
	book.price = 500;
    book.type = "Mythological Fiction";
    book.author = "Amish Tripathi";
	book.publicationName = "Rupa publications";
	book.noOfPages = 1000;
	book.gainKnowledge();
	//System.out.println(book5.name +" "+ book5.type + " " + book5.price + " " + book5.author + " " + book5.publicationName + " " + book5.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 7th copy of the Book");
    //Book book6 = new Book();
	book.name = "A Suitable Boy";
	book.price = 200;
    book.type = "Fiction";
    book.author = "Vikram Seth";
	book.publicationName = "Ram publications";
	book.noOfPages = 300;
	book.gainKnowledge();
	//System.out.println(book6.name +" "+ book6.type + " " + book6.price + " " + book6.author + " " + book6.publicationName + " " + book6.noOfPages);
    System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 8th copy of the Book");
    //Book book7 = new Book();
	book.name = "Interpreter of Maladies";
	book.price = 200;
    book.type = "Short Stories";
    book.author = "Jhumpa Lahiri";
	book.publicationName = "Mathi books";
	book.noOfPages = 250;
	book.gainKnowledge();
	//System.out.println(book7.name +" "+ book7.type + " " + book7.price + " " + book7.author + " " + book7.publicationName + " " + book7.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 9th copy of the Book");
    //Book book8 = new Book();
	book.name = "The Rozabal Line";
	book.price = 600;
    book.type = "Thriller";
    book.author = "Ashwin Sanghi";
	book.publicationName = "Ram books";
	book.noOfPages = 300;
	book.gainKnowledge();
	//System.out.println(book8.name +" "+ book8.type + " " + book8.price + " " + book8.author + " " + book8.publicationName + " " + book8.noOfPages);
	System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 10th copy of the Book");
    //Book book9 = new Book();
	book.name = "Five Point Someone";
	book.price = 500;
    book.type = "Fiction";
    book.author = "Chetan Bhagat";
	book.publicationName = "Ganga books";
	book.noOfPages = 600;
	book.gainKnowledge();
	//System.out.println(book9.name +" "+ book9.type + " " + book9.price + " " + book9.author + " " + book9.publicationName + " " + book9.noOfPages);
    System.out.println(book.name);
    System.out.println(book.type);
    System.out.println(book.price);	
	System.out.println(book.author);
	System.out.println(book.publicationName);
	System.out.println(book.noOfPages);
	
	}

}
