class ChocolatesTester{
    public static void main(String choco[]){
	System.out.println("Creating 1st copy of the Chocolates");
    Chocolates chocolates = new Chocolates();
	chocolates.name = "Cadbury Dairy Milk";
	chocolates.flavor = "Milk Chocolate";
    chocolates.price = 20;
    chocolates.quantity = "50g";
	chocolates.expDate = "2023-12-31";
	chocolates.mgfDate = "2023-07-01";
	chocolates.toGetColories();
	//System.out.println(chocolates.name +" "+ chocolates.flavor + " " + chocolates.price + " " + chocolates.quantity + " " + chocolates.expDate + " " + chocolates.mgfDate);
    System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 2nd copy of the Chocolates");
    //Chocolates chocolates1 = new Chocolates();
	chocolates.name = "Amul Dark Chocolate";
	chocolates.flavor = "Dark Chocolate";
    chocolates.price = 25;
    chocolates.quantity = "40g";
	chocolates.expDate = "2024-02-28";
	chocolates.mgfDate = "2023-10-15";
	chocolates.toGetColories();
	//System.out.println(chocolates1.name +" "+ chocolates1.flavor + " " + chocolates1.price + " " + chocolates1.quantity + " " + chocolates1.expDate + " " + chocolates1.mgfDate);
    System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 3rd copy of the Chocolates");
    //Chocolates chocolates2 = new Chocolates();
	chocolates.name = "KitKat";
	chocolates.flavor = "Wafer and Milk Chocolate";
    chocolates.price = 10;
    chocolates.quantity = "35g";
	chocolates.expDate = "2023-11-30";
	chocolates.mgfDate = "2023-06-05";
	chocolates.toGetColories();
	//System.out.println(chocolates2.name +" "+ chocolates2.flavor + " " + chocolates2.price + " " + chocolates2.quantity + " " + chocolates2.expDate + " " + chocolates2.mgfDate);
    System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 4th copy of the Chocolates");
    //Chocolates chocolates3 = new Chocolates();
	chocolates.name = "Ferrero Rocher";
	chocolates.flavor = "nut and Chocolate";
    chocolates.price = 150;
    chocolates.quantity = "200g";
	chocolates.expDate = "2024-05-31";
	chocolates.mgfDate = "2023-12-15";
	chocolates.toGetColories();
	//System.out.println(chocolates3.name +" "+ chocolates3.flavor + " " + chocolates3.price + " " + chocolates3.quantity + " " + chocolates3.expDate + " " + chocolates3.mgfDate);
	System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 5th copy of the Chocolates");
    //Chocolates chocolates4 = new Chocolates();
	chocolates.name = "Bournville Rich Cocoa";
	chocolates.flavor = "Dark Chocolate";
    chocolates.price = 30;
    chocolates.quantity = "80g";
	chocolates.expDate = "2023-10-31";
	chocolates.mgfDate = "2023-04-20";
	chocolates.toGetColories();
	//System.out.println(chocolates4.name +" "+ chocolates4.flavor + " " + chocolates4.price + " " + chocolates4.quantity + " " + chocolates4.expDate + " " + chocolates4.mgfDate);
	System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 6th copy of the Chocolates");
    //Chocolates chocolates5 = new Chocolates();
	chocolates.name = "Mars";
	chocolates.flavor = "Milk Chocolate and Caramel";
    chocolates.price = 15;
    chocolates.quantity = "51g";
	chocolates.expDate = "2024-03-31";
	chocolates.mgfDate = "2023-12-05";
	chocolates.toGetColories();
	//System.out.println(chocolates5.name +" "+ chocolates5.flavor + " " + chocolates5.price + " " + chocolates5.quantity + " " + chocolates5.expDate + " " + chocolates5.mgfDate);
	System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 7th copy of the Chocolates");
    //Chocolates chocolates6 = new Chocolates();
	chocolates.name = "Galaxy Smooth Milk";
	chocolates.flavor = "Milk Chocolate";
    chocolates.price = 35;
    chocolates.quantity = "100g";
	chocolates.expDate = "2024-01-31";
	chocolates.mgfDate = "2023-09-10";
	chocolates.toGetColories();
	//System.out.println(chocolates6.name +" "+ chocolates6.flavor + " " + chocolates6.price + " " + chocolates6.quantity + " " + chocolates6.expDate + " " + chocolates6.mgfDate);
    System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 8th copy of the Chocolates");
    //Chocolates chocolates7 = new Chocolates();
	chocolates.name = "Perk";
	chocolates.flavor = "Milk Chocolate and Crispy Rice";
    chocolates.price = 5;
    chocolates.quantity = "15g";
	chocolates.expDate = "2023-09-30";
	chocolates.mgfDate = "2023-05-20";
	chocolates.toGetColories();
	//System.out.println(chocolates7.name +" "+ chocolates7.flavor + " " + chocolates7.price + " " + chocolates7.quantity + " " + chocolates7.expDate + " " + chocolates7.mgfDate);
	System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 9th copy of the Chocolates");
    //Chocolates chocolates8 = new Chocolates();
	chocolates.name = "Lindt Excellence";
	chocolates.flavor = "Cocoa Dark Chocolate";
    chocolates.price = 100;
    chocolates.quantity = "100g";
	chocolates.expDate = "2024-04-30";
	chocolates.mgfDate = "2023-12-01";
	chocolates.toGetColories();
	//System.out.println(chocolates8.name +" "+ chocolates8.flavor + " " + chocolates8.price + " " + chocolates8.quantity + " " + chocolates8.expDate + " " + chocolates8.mgfDate);
	System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 10th copy of the Chocolates");
    //Chocolates chocolates9 = new Chocolates();
	chocolates.name = "Toblerone";
	chocolates.flavor = "Milk Chocolate with Honey";
    chocolates.price = 80;
    chocolates.quantity = "100g";
	chocolates.expDate = "2024-07-15";
	chocolates.mgfDate = "2024-01-15";
	chocolates.toGetColories();
	//System.out.println(chocolates9.name +" "+ chocolates9.flavor + " " + chocolates9.price + " " + chocolates9.quantity + " " + chocolates9.expDate + " " + chocolates9.mgfDate);
    System.out.println(chocolates.name);
    System.out.println(chocolates.flavor);
    System.out.println(chocolates.price);	
	System.out.println(chocolates.quantity);
	System.out.println(chocolates.expDate);
	System.out.println(chocolates.mgfDate);
	}

}
