class ClockTester{
    public static void main(String time[]){
	System.out.println("Creating 1st copy of the Clock");
    Clock clock = new Clock();
	clock.name = "Seiko Wall Clock";
	clock.price = 1500;
    clock.size = "12 inches";
	clock.color = "Black";
	clock.toKnowTime();
	//System.out.println(clock.name +" "+ clock.price + " " + clock.size + " " + clock.color);
    System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 2nd copy of the Clock");
    //Clock clock1 = new Clock();
	clock.name = "Ajanta Analog Table Clock";
	clock.price = 800;
    clock.size = "6 inches";
	clock.color = "White";
	clock.toKnowTime();
	//System.out.println(clock1.name +" "+ clock1.price + " " + clock1.size + " " + clock1.color);
	System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 3rd copy of the Clock");
    //Clock clock2 = new Clock();
	clock.name = "Casio Digital Alarm Clock";
	clock.price = 1000;
    clock.size = "4 inches";
	clock.color = "Silver";
	clock.toKnowTime();
	//System.out.println(clock2.name +" "+ clock2.price + " " + clock2.size + " " + clock2.color);
	System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 4th copy of the Clock");
    //Clock clock3 = new Clock();
	clock.name = "Rhythm Musical Wall Clock";
	clock.price = 2500;
    clock.size = "14 inches";
	clock.color = "Brown";
	clock.toKnowTime();
	//System.out.println(clock3.name +" "+ clock3.price + " " + clock3.size + " " + clock3.color);
    System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 5th copy of the Clock");
    //Clock clock4 = new Clock();
	clock.name = "Havells Decorative Pendulum Clock";
	clock.price = 2000;
    clock.size = "18 inches";
	clock.color = "Gold";
	clock.toKnowTime();
	//System.out.println(clock4.name +" "+ clock4.price + " " + clock4.size + " " + clock4.color);
	System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 6th copy of the Clock");
    //Clock clock5 = new Clock();
	clock.name = "Citizen Table Clock";
	clock.price = 1300;
    clock.size = "8 inches";
	clock.color = "Silver";
	clock.toKnowTime();
	//System.out.println(clock.name +" "+ clock.price + " " + clock.size + " " + clock.color);
	System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 7th copy of the Clock");
    //Clock clock6 = new Clock();
	clock.name = "Panasonic Digital LED Alarm Clock";
	clock.price = 1200;
    clock.size = "5 inches";
	clock.color = "Blue";
	clock.toKnowTime();
	//System.out.println(clock6.name +" "+ clock6.price + " " + clock6.size + " " + clock6.color);
	System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 8th copy of the Clock");
    //Clock clock7 = new Clock();
	clock.name = "Orpat Quartz Round Wall Clock";
	clock.price = 700;
    clock.size = "10 inches";
	clock.color = "Red";
	clock.toKnowTime();
	//System.out.println(clock7.name +" "+ clock7.price + " " + clock7.size + " " + clock7.color);
    System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 9th copy of the Clock");
    //Clock clock8 = new Clock();
	clock.name = "Opal Decorative Cuckoo Clock";
	clock.price = 3000; 
    clock.size = "16 inches";
	clock.color = "Green";
	clock.toKnowTime();
	//System.out.println(clock8.name +" "+ clock8.price + " " + clock8.size + " " + clock8.color);
	System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
    System.out.println("---------------------------------");
	
	System.out.println("Creating 10th copy of the Clock");
    //Clock clock9 = new Clock();
	clock.name = "Timex Retro Flip Clock";
	clock.price = 1800;
    clock.size = "9 inches";
	clock.color = "Black and White";
	clock.toKnowTime();
	//System.out.println(clock9.name +" "+ clock9.price + " " + clock9.size + " " + clock9.color);
	System.out.println(clock.name);
    System.out.println(clock.price);
	System.out.println(clock.size);
    System.out.println(clock.color);	
	}
}