class SnacksTester{
    public static void main(String eat[]){
	System.out.println("Creating 1st copy of the Snacks");
    Snacks snacks = new Snacks();
	snacks.name = "Lays Classic Potato Chips";
	snacks.price = 10;
    snacks.color = "Yellow Packet";
	snacks.size = "30g";
	snacks.toEat();
	//System.out.println(snacks.name +" "+ snacks.price + " " + snacks.color + " " + snacks.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");

	System.out.println("Creating 2nd copy of the Snacks");
    //Snacks snacks1 = new Snacks();
	snacks.name = "Kurkure Masala Munch";
	snacks.price = 10;
    snacks.color = "Red Packet";
	snacks.size = "35g";
	snacks.toEat();
	//System.out.println(snacks1.name +" "+ snacks1.price + " " + snacks1.color + " " + snacks1.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 3rd copy of the Snacks");
    //Snacks snacks2 = new Snacks();
	snacks.name = "Bingo Mad Angles";
	snacks.price = 15;
    snacks.color = "Green Packet";
	snacks.size = "40g";
	snacks.toEat();
	//System.out.println(snacks2.name +" "+ snacks2.price + " " + snacks2.color + " " + snacks2.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 4th copy of the Snacks");
    //Snacks snacks3 = new Snacks();
	snacks.name = "Haldiram's Aloo Bhujia";
	snacks.price = 40;
    snacks.color = "Purple Packet";
	snacks.size = "400g";
	snacks.toEat();
	//System.out.println(snacks3.name +" "+ snacks3.price + " " + snacks3.color + " " + snacks3.size );
    System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 5th copy of the Snacks");
    //Snacks snacks4 = new Snacks();
	snacks.name = "Britannia Bourbon Biscuits";
	snacks.price = 20;
    snacks.color = "Blue Packet";
	snacks.size = "150g";
	snacks.toEat();
	//System.out.println(snacks4.name +" "+ snacks4.price + " " + snacks4.color + " " + snacks4.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 6th copy of the Snacks");
    //Snacks snacks5 = new Snacks();
	snacks.name = "Parle-G Glucose Biscuits";
	snacks.price = 10;
    snacks.color = "Yellow Packet";
	snacks.size = "100g";
	snacks.toEat();
	//System.out.println(snacks5.name +" "+ snacks5.price + " " + snacks5.color + " " + snacks5.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 7th copy of the Snacks");
    //Snacks snacks6 = new Snacks();
	snacks.name = "Maggi Instant Noodles";
	snacks.price = 10;
    snacks.color = "Yellow Packet";
	snacks.size = "100g";
	snacks.toEat();
	//System.out.println(snacks6.name +" "+ snacks6.price + " " + snacks6.color + " " + snacks6.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");

    System.out.println("Creating 8th copy of the Snacks");
    //Snacks snacks7 = new Snacks();
	snacks.name = "Bikano Moong Dal";
	snacks.price = 50;
    snacks.color = "Green Packet";
	snacks.size = "400g";
	snacks.toEat();
	//System.out.println(snacks7.name +" "+ snacks7.price + " " + snacks7.color + " " + snacks7.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 9th copy of the Snacks");
    //Snacks snacks8 = new Snacks();
	snacks.name = "Popcorn";
	snacks.price = 30;
    snacks.color = "Brown Packet";
	snacks.size = "90g";
	snacks.toEat();
	//System.out.println(snacks8.name +" "+ snacks8.price + " " + snacks8.color + " " + snacks8.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
    System.out.println("---------------------------------");
	
	System.out.println("Creating 10th copy of the Snacks");
    //Snacks snacks9 = new Snacks();
	snacks.name = "Potato Stricks";
	snacks.price = 25;
    snacks.color = "Orange Packet";
	snacks.size = "75g";
	snacks.toEat();
	//System.out.println(snacks9.name +" "+ snacks9.price + " " + snacks9.color + " " + snacks9.size );
	System.out.println(snacks.name);
    System.out.println(snacks.price);
    System.out.println(snacks.color);	
    System.out.println(snacks.size);
	}
}