class SuitCaseTester{
    public static void main(String s[]){
    System.out.println("1st copy of suitcase");
    SuitCase suitCase= new SuitCase();
    suitCase.brandName= "Skybags";
    suitCase.weight= "1kg";
    suitCase.price=500;
    suitCase.noOfPockets=2;
    suitCase.forLuggage();
    //System.out.println(suitCase.brandName + " is a brand of suitcase  " +suitCase.weight + " is a weight of suitcase  " +suitCase.price + " is a price of suitcase " + suitCase.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("2nd copy of suitcase");
    //SuitCase suitCase1= new SuitCase();
    suitCase.brandName= "safari";
    suitCase.weight= "2kg";
    suitCase.price=600;
    suitCase.noOfPockets=1;
    suitCase.forLuggage();
    //System.out.println(suitCase1.brandName + " is a brand of suitcase  " +suitCase1.weight + " is a weight of suitcase  " +suitCase1.price + " is a price of suitcase " + suitCase1.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("3rd copy of suitcase");
    //SuitCase suitCase2= new SuitCase();
    suitCase.brandName= "wildcraft";
    suitCase.weight= "3kg";
    suitCase.price=900;
    suitCase.noOfPockets=6;
    suitCase.forLuggage();
    //System.out.println(suitCase2.brandName + " is a brand of suitcase  " +suitCase2.weight + " is a weight of suitcase  " +suitCase2.price + " is a price of suitcase " + suitCase2.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("4th copy of suitcase");
    //SuitCase suitCase3= new SuitCase();
    suitCase.brandName= "Tumi";
    suitCase.weight= "4kg";
    suitCase.price=1000;
    suitCase.noOfPockets=3;
    suitCase.forLuggage();
    //System.out.println(suitCase3.brandName + " is a brand of suitcase  " +suitCase3.weight + " is a weight of suitcase  " +suitCase3.price + " is a price of suitcase " + suitCase3.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("5th copy of suitcase");
    //SuitCase suitCase4= new SuitCase();
    suitCase.brandName= "samsonite";
    suitCase.weight= "5kg";
    suitCase.price=500;
    suitCase.noOfPockets=3;
    suitCase.forLuggage();
    //System.out.println(suitCase4.brandName + " is a brand of suitcase  " +suitCase4.weight + " is a weight of suitcase  " +suitCase4.price + " is a price of suitcase " + suitCase4.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("6th copy of suitcase");
    //SuitCase suitCase5= new SuitCase();
    suitCase.brandName= "safari";
    suitCase.weight= "6kg";
    suitCase.price=1500;
    suitCase.noOfPockets=2;
    suitCase.forLuggage();
    //System.out.println(suitCase5.brandName + " is a brand of suitcase  " +suitCase5.weight + " is a weight of suitcase  " +suitCase5.price + " is a price of suitcase " + suitCase5.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("7th copy of suitcase");
    //SuitCase suitCase6= new SuitCase();
    suitCase.brandName= "Skybags";
    suitCase.weight= "7kg";
    suitCase.price=1600;
    suitCase.noOfPockets=4;
    suitCase.forLuggage();
    //System.out.println(suitCase6.brandName + " is a brand of suitcase  " +suitCase6.weight + " is a weight of suitcase  " +suitCase6.price + " is a price of suitcase " + suitCase6.noOfPockets + " is a number of pockets in suitcase"  );
	System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
	System.out.println("8th copy of suitcase");
	//SuitCase suitCase7= new SuitCase();
    suitCase.brandName= "wildcraft";
    suitCase.weight= "1kg";
    suitCase.price=6500;
    suitCase.noOfPockets=2;
    suitCase.forLuggage();
    //System.out.println(suitCase7.brandName + " is a brand of suitcase  " +suitCase7.weight + " is a weight of suitcase  " +suitCase7.price + " is a price of suitcase " + suitCase7.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("9th copy of suitcase");
    //SuitCase suitCase8= new SuitCase();
    suitCase.brandName= "tumi";
    suitCase.weight= "2kg";
    suitCase.price=7500;
    suitCase.noOfPockets=5;
    suitCase.forLuggage();
    //System.out.println(suitCase8.brandName + " is a brand of suitcase  " +suitCase8.weight + " is a weight of suitcase  " +suitCase8.price + " is a price of suitcase " + suitCase8.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
    System.out.println("---------------------------------");
	
    System.out.println("10th copy of suitcase");
    //SuitCase suitCase9= new SuitCase();
    suitCase.brandName= "Skybags";
    suitCase.weight= "1kg";
    suitCase.price=5600;
    suitCase.noOfPockets=2;
    suitCase.forLuggage();
    //System.out.println(suitCase9.brandName + " is a brand of suitcase  " +suitCase9.weight + " is a weight of suitcase  " +suitCase9.price + " is a price of suitcase " + suitCase9.noOfPockets + " is a number of pockets in suitcase"  );
    System.out.println(suitCase.brandName);
    System.out.println(suitCase.weight);
    System.out.println(suitCase.price);	
	System.out.println(suitCase.noOfPockets);
}
}