class ZomatoTester{
   public static void main(String foodDelivery[]){
   
      String foodName ="Pizza";
	  double priceOfFoodName =Zomato.search (foodName);
	  System.out.println("The Price is " +priceOfFoodName);
	  double priceWithGivenQuantity=Zomato.search("Pizza",5);
	  System.out.println("The food price with quntity " +priceWithGivenQuantity);
	  System.out.println("-----------------------------");
	  String foodName1 ="Chicken Biriyani";
	  double priceOfFoodName1 =Zomato.search (foodName1);
	  System.out.println("The Price is " +priceOfFoodName1);
	  double priceWithGivenQuantity1 =Zomato.search("Chicken Biriyani",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity1);	  
	  System.out.println("-----------------------------");
	  String foodName2 ="Burger";
	  double priceOfFoodName2 =Zomato.search (foodName2);
	  System.out.println("The Price is " +priceOfFoodName2);
	   double priceWithGivenQuantity2 =Zomato.search("Burger",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity2);	  
	  System.out.println("-----------------------------");
	  String foodName3 ="Dosa";
	  double priceOfFoodName3 =Zomato.search (foodName3);
	  System.out.println("The Price is " +priceOfFoodName3);
	   double priceWithGivenQuantity3 =Zomato.search("Dosa",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity3);	  
	  System.out.println("-----------------------------");
	  String foodName4 ="Rice Bath";
	  double priceOfFoodName4 =Zomato.search (foodName4);
	  System.out.println("The Price is " +priceOfFoodName4);
	   double priceWithGivenQuantity4 =Zomato.search("Rice Bath",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity4);	  
	  System.out.println("-----------------------------");
	  String foodName5 ="ice cream";
	  double priceOfFoodName5 =Zomato.search (foodName5);
	  System.out.println("The Price is " +priceOfFoodName5);
	   double priceWithGivenQuantity5 =Zomato.search("ice cream",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity5);	  
	  System.out.println("-----------------------------");
	  String foodName6 ="Chilly Chicken";
	  double priceOfFoodName6 =Zomato.search (foodName6);
	  System.out.println("The Price is " +priceOfFoodName6);
	   double priceWithGivenQuantity6 =Zomato.search("Chilly Chicken",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity6);	  
	  System.out.println("-----------------------------");
	  String foodName7 ="vada";
	  double priceOfFoodName7 =Zomato.search (foodName7);
	  System.out.println("The Price is " +priceOfFoodName7);
	   double priceWithGivenQuantity7 =Zomato.search("vada",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity7);	  
	  System.out.println("-----------------------------");
	  String foodName8 ="veg roll";
	  double priceOfFoodName8 =Zomato.search (foodName8);
	  System.out.println("The Price is " +priceOfFoodName8);
	   double priceWithGivenQuantity8 =Zomato.search("veg roll",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity8);	  
	  System.out.println("-----------------------------");
	  String foodName9 ="non-veg roll";
	  double priceOfFoodName9 =Zomato.search (foodName9);
	  System.out.println("The Price is " +priceOfFoodName9);
	   double priceWithGivenQuantity9 =Zomato.search("non-veg roll",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity9);	  
	  System.out.println("-----------------------------");
	  String foodName10 ="cake";
	  double priceOfFoodName10 =Zomato.search (foodName10);
	  System.out.println("The Price is " +priceOfFoodName10);
	   double priceWithGivenQuantity10 =Zomato.search("cake",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity10);	  
	  System.out.println("-----------------------------");
	  String foodName11 ="pani puri";
	  double priceOfFoodName11 =Zomato.search (foodName11);
	  System.out.println("The Price is " +priceOfFoodName11);
	   double priceWithGivenQuantity11 =Zomato.search("pani puri",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity11);	  
	  System.out.println("-----------------------------");
	  String foodName12 ="Noodles";
	  double priceOfFoodName12 =Zomato.search (foodName12);
	  System.out.println("The Price is " +priceOfFoodName12);
	   double priceWithGivenQuantity12 =Zomato.search("Noodles",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity12);	  
	  System.out.println("-----------------------------");
	  String foodName13 ="french fries";
	  double priceOfFoodName13 =Zomato.search (foodName13);
	  System.out.println("The Price is " +priceOfFoodName13);
	   double priceWithGivenQuantity13 =Zomato.search("french fries",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity13);	  
	  System.out.println("-----------------------------");
	  String foodName14 ="butter naan";
	  double priceOfFoodName14 =Zomato.search (foodName14);
	  System.out.println("The Price is " +priceOfFoodName14);
	   double priceWithGivenQuantity14 =Zomato.search("butter naan",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity14);	  
	  System.out.println("-----------------------------");
	  String foodName15 ="Kabab";
	  double priceOfFoodName15 =Zomato.search (foodName15);
	  System.out.println("The Price is " +priceOfFoodName15);
	   double priceWithGivenQuantity15 =Zomato.search("Kabab",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity15);	  
	  System.out.println("-----------------------------");
	  String foodName16 ="Mushroom Biriyani";
	  double priceOfFoodName16 =Zomato.search (foodName16);
	  System.out.println("The Price is " +priceOfFoodName16);
	   double priceWithGivenQuantity16 =Zomato.search("Mushroom Biriyani",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity16);	  
	  System.out.println("-----------------------------");
	  String foodName17 ="Soup";
	  double priceOfFoodName17 =Zomato.search (foodName17);
	  System.out.println("The Price is " +priceOfFoodName17);
	   double priceWithGivenQuantity17 =Zomato.search("Soup",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity17);	  
	  System.out.println("-----------------------------");
	  String foodName18 ="Roti";
	  double priceOfFoodName18 =Zomato.search (foodName18);
	  System.out.println("The Price is " +priceOfFoodName18);
	   double priceWithGivenQuantity18 =Zomato.search("Roti",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity18);	  
	  System.out.println("-----------------------------");
	  String foodName19 ="gobi";
	  double priceOfFoodName19 =Zomato.search (foodName19);
	  System.out.println("The Price is " +priceOfFoodName19);
	   double priceWithGivenQuantity19 =Zomato.search("gobi",5);
      System.out.println("The food price with quntity " +priceWithGivenQuantity19);	  
   }
   
 
}